### ISSUE TITLE
Crash with latest Android studio version

### ISSUE THREAD

**Issue by PolestarApplab** [2i18ns/i18ns.com#2]
java.lang.StringIndexOutOfBoundsException: String index out of range: -8
	at java.lang.String.substring(String.java:1967)
	at model.AndroidString.getAndroidStringsList(AndroidString.java:171)
	at action.I18nsRobotAction.isNotEnglishContent(I18nsRobot.kt:127)
	at action.I18nsRobotAction.actionPerformed(I18nsRobot.kt:55)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)

**Comment by 2i18ns** [comment]
Thank for you feedback.

From the log you reported,  the string name may be is not recognized properly. can you provide the string you want translated.

**Comment by 2i18ns** [comment]
> java.lang.StringIndexOutOfBoundsException: String index out of range: -8
> at java.lang.String.substring(String.java:1967)
> at model.AndroidString.getAndroidStringsList(AndroidString.java:171)
> at action.I18nsRobotAction.isNotEnglishContent(I18nsRobot.kt:127)
> at action.I18nsRobotAction.actionPerformed(I18nsRobot.kt:55)
> at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
> at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
> at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
> at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
> at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)

Thank for you feedback.

From the log you reported, the string name may be is not recognized properly. can you provide the string you want translated.
